### PR TITLE
fixed app width, added other organizers, fixed blurry logo

### LINKED ISSUE #3: Update the Organizers page
Image

- [ ] Add all organizers to this page
- [ ] Each organizer should include their picture and full name (you can find these on LinkedIn)

### LINKED ISSUE #5: Improvements
- [ ] Fix blurry logo (see new logo file in the comments)
- [ ] Add max-width 480px to the page layout and keep the page centered
- [ ] Add background image to the website (see comments)

### PR DESCRIPTION
**Pull request by IgorTheFixer**

### CODE REVIEW

File: components/Card.tsx
Comment (alexpereira) [inline components/Card.tsx:1]: Is this being used?

File: components/layout/Logo.tsx [hunk 1]
```diff
@@ -1,10 +1,13 @@
-import Image from "next/image";
-import ccLogo from "./logo.png";
```
Comment (alexpereira) [inline components/layout/Logo.tsx:2]: We should delete this logo.png file from the codebase as well, unless it's used somewhere else

File: components/layout/Logo.tsx [hunk 2]
```diff
@@ -1,10 +1,13 @@
...
+      </defs>
+    </svg>
```
Comment (alexpereira) [inline components/layout/Logo.tsx:11]: Storing svg data as code is great for things like icons so you can manipulate them

However I would keep the logo in its own `logo.svg` file, just like the old `.png` file, in case we need to use it outside of tsx later on.

File: components/layout/NavBar.tsx [hunk 3]
```diff
@@ -1,13 +1,15 @@
-import Logo from "./Logo";
+import Logo from "../layout/Logo"
 import Link from "next/link";
 
 export default function NavBar() {
   return (
-    <nav className="mx-auto max-w-7xl px-5 mb-9">
+    // <nav className="mx-auto max-w-7xl px-5 mb-9">
```
Comment (alexpereira) [inline components/layout/NavBar.tsx]: are we planning to reuse commented-out code like this one?

File: components/layout/Wrapper.tsx [hunk 4]
```diff
@@ -1,7 +1,8 @@
 
 export default function Wrapper({children, title, description}: any) {
   return (
-    <div className="isolate bg-white px-6 py-24 sm:py-32 lg:px-8">
+    // <div className="isolate bg-white px-6 py-24 sm:py-32 lg:px-8">
```
Comment (alexpereira) [inline components/layout/Wrapper.tsx]: +1

File: app/organizers/page.tsx [hunk 5]
```diff
@@ -8,19 +8,29 @@ const team = [
...
+    role: "Co-Organizer",
+    imageUrl:
+    "https://media.licdn.com/dms/image/C5603AQF4XNgseUCHyQ/profile-displayphoto-shrink_400_400/0/1655003018441?e=1694044800&v=beta&t=PCruuX2t6f9IkQ92e_z-OdSDIR2Qpf5WOuM7eOQ7KbM"
+  },
+  {
+    name: "Anton Shelkovnikov",
+    role: "Co-Organizer",
+    imageUrl:
+    "https://media.licdn.com/dms/image/C4E03AQHKGkWJ9knk4A/profile-displayphoto-shrink_400_400/0/1652227805550?e=1694044800&v=beta&t=FxfNvYBDkdkeTIl2SlBYJK4UWvhcY3GWBrzxbA64hsE"
+  },
```
Comment (alexpereira) [inline app/organizers/page.tsx:22]: The mock also has this other person Jarrod Kohl. Do we need to add them here?

https://www.figma.com/proto/6ti3DRuiTWDEjgD8aWLVWA/Boston-Code-%26-Coffee?node-id=409-42&starting-point-node-id=1%3A26

File: app/organizers/page.tsx [hunk 6]
```diff
@@ -8,19 +8,29 @@ const team = [
...
 ];
 
 export default function Organizers() {
   return (
 
     <Wrapper title="Team" description="Describe what this is about.">
```
Comment (alexpereira) [inline app/organizers/page.tsx]: In the description text, we can make it "Meet our Organizers!" to match the mock more closely

**Comment by alexpereira** [comment]
Added the background images in commit f824f1f

**Review by alexpereira — APPROVED** [review]
